version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - 0.0.0.0:27017:27017
    volumes:
        - <bind mount host volume>:/data/db
    env_file: .env
    expose:
      - 27017
    networks:
      - omniboard

  omniboard:
    image: omniboard:release
    build: 
      context: ./omniboard
      dockerfile: dockerfile
    ports:
      - 0.0.0.0:9000:9000
    networks:
      - omniboard
    depends_on:
      - mongo

networks:
  omniboard:
