version: '3.3'

services:
  sklearn_deploy:
    container_name: sklearn_release
    extends:
      file: ../common-compose.yml
      service: sklearn
    env_file:
      - ../.env
    shm_size: '20gb' # using ray shared memory option.
    command:
      sh -c "cd ${PYTHONPATH}/celery && ./run-celery.sh"

  flask_deploy:
    container_name: flask_release
    extends:
      file: ../common-compose.yml
      service: flask
    env_file:
      - ../.env
    ports:
      - 0.0.0.0:5500:5500
    command:
      sh -c "cd ${PYTHONPATH}/web && ./run-flask.sh"
