version: '3'
services:
  mongo1:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ${MONGODB_REPL_1_PATH}:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
  mongo2:
    image: "mongo"
    ports:
      - "27018:27017"
    volumes:
      - ${MONGODB_REPL_2_PATH}:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo1
  mongo3:
    image: "mongo"
    ports:
      - "27019:27017"
    volumes:
      - ${MONGODB_REPL_3_PATH}:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo2
  mongosetup:
    image: "setup-rspl"
    depends_on:
      - mongo1
    networks:
      - mongo-networks

networks:
  mongo-networks:
    driver: bridge
